# Generated by Django 5.2.6 on 2026-02-11 07:15

from django.db import migrations, models


def copy_product_images(apps, schema_editor):
    """Copy ProductImage data to Product image fields"""
    Product = apps.get_model('products', 'Product')
    ProductImage = apps.get_model('products', 'ProductImage')
    
    for product in Product.objects.all():
        # Get all images for this product, ordered by display_order
        images = ProductImage.objects.filter(product=product).order_by('display_order', 'created_at')[:4]
        
        # Assign images to the product fields
        for idx, img in enumerate(images):
            if idx == 0:
                product.image = img.image
            elif idx == 1:
                product.image_2 = img.image
            elif idx == 2:
                product.image_3 = img.image
            elif idx == 3:
                product.image_4 = img.image
        
        if images.exists():
            product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_cakedesignreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Main product image', null=True, upload_to='products/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Additional image 2', null=True, upload_to='products/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Additional image 3', null=True, upload_to='products/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, help_text='Additional image 4', null=True, upload_to='products/%Y/%m/%d/'),
        ),
        migrations.RunPython(copy_product_images, reverse_code=migrations.RunPython.noop),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
