# Generated by Django 5.2.8 on 2026-01-17 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_payment_status'),
        ('products', '0005_delete_cakedesignreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeCustomization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cake_flavor', models.CharField(blank=True, max_length=100)),
                ('cake_custom_flavor', models.CharField(blank=True, max_length=200)),
                ('cake_weight', models.CharField(blank=True, max_length=50)),
                ('cake_custom_weight', models.CharField(blank=True, max_length=50)),
                ('cake_tiers', models.IntegerField(default=1)),
                ('message_on_cake', models.CharField(blank=True, max_length=100)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='cake_designs/%Y/%m/%d/')),
                ('reference_title', models.CharField(blank=True, max_length=200)),
                ('reference_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cake_customizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cake Customization',
                'verbose_name_plural': 'Cake Customizations',
                'ordering': ['-created_at'],
            },
        ),
    ]
