# Generated by Django 5.2.8 on 2026-01-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.CreateModel(
            name='BakeryAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'admin/owner',
                'verbose_name_plural': 'admins/owners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuser',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'staff members',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuser',),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='customuser',
            name='primary_address',
            field=models.TextField(blank=True, help_text='Primary address for staff members', verbose_name='primary address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('admin', 'Admin/Owner')], default='customer', max_length=10, verbose_name='user type'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
