# Generated by Django 5.2.8 on 2026-01-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_address_customer_delete_admin_bakeryadmin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BakeryAdmin',
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
            ],
            options={
                'verbose_name': 'owner/superuser',
                'verbose_name_plural': 'owners/superusers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuser',),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('owner', 'Owner/Superuser')], default='customer', max_length=10, verbose_name='user type'),
        ),
    ]
