# Generated by Django 5.2.6 on 2026-01-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remembermetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_login_completed',
            field=models.BooleanField(default=False, help_text='Tracks whether user has completed their first login', verbose_name='first login completed'),
        ),
    ]
