# Generated by Django 5.2.8 on 2026-01-05 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_fee_order_subtotal_and_more'),
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payment_pay_order_i_24b05e_idx',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='order_id',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['order'], name='payment_pay_order_i_24b05e_idx'),
        ),
    ]
