# Generated by Django 5.2.8 on 2026-01-05 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_fee_order_subtotal_and_more'),
        ('payment', '0002_remove_paymenttransaction_payment_pay_order_i_24b05e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user'], name='payment_pay_user_id_ca2927_idx'),
        ),
    ]
